name: CI Checks
on:
   pull_request:
     branches: ['main']
   push :
     branches: ['main']  

env: 
  NODE_VERSION: 18.x

jobs: 
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [frontend, backend]


    steps:
      - name: Checkout code 
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: 'npm'

      - name: Install dependencies 
        working-directory: ${{ matrix.app }}
        run: npm ci

      - name: Run ESLint (${{matrix.app}})
        working-directory: ${{ matrix.app }}
        run: npm run lint || echo "Lint failed, for ${{ matrix.app }}"

      - name: Run Tests 
        working-directory: ${{ matrix.app }}
        run: npm test -- --watchAll=false --coverage

      - name: Build frontend
        if: matrix.app == 'frontend'
        working-directory: frontend
        run: npm run build
        